### ISSUE TITLE
URI設計

### ISSUE THREAD

**Issue by IkumaTadokoro** [IkumaTadokoro/quitcost#11]

**Comment by IkumaTadokoro** [comment]
| Method | Path | Description |
| --- | --- | --- |
| GET | / | トップページ |
| POST | /simulations | 試算を実行する |
| GET | /simulations | 試算結果を表示する |
| GET | /login | 管理者ログインページを表示 |
| POST | /login | 管理者ログイン |
| DELETE | /logout | 管理者ログアウト |
| GET | /insurances | 国民健康保険料一覧を表示する |
| POST | /insurances | 国民健康保険料を登録する |
| PUT | /insurances/:id | 国民健康保険料を更新する |
| DELETE | /insurances/:id | 国民健康保険料を削除する |
| GET | /pentions | 国民年金保険料一覧を表示する |
| POST | /pentions | 国民年金保険料を登録する |
| PUT | /pentions/:id | 国民年金保険料を更新する |
| DELETE | /pentions/:id | 国民年金保険料を削除する |

試算のフォーム→試算結果のURLをどうするか悩み中

**Comment by komagata** [comment]
@IkumaTadokoro 

> 試算結果の部分をsimulationにしていますが、複数形にすべきか悩み中です。

たくさんsimulationがあるわけでなければ単数系でいいと思います〜。

他も問題なさそうです〜

**Comment by IkumaTadokoro** [comment]
@komagata 
レビューいただきありがとうございました🙇‍♂️

> たくさんsimulationがあるわけでなければ単数系でいいと思います〜。

計算は一回きりで保存しないので、単数系で進めたいと思います〜。
