### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by IkumaTadokoro** [IkumaTadokoro/quitcost#4]

**Comment by IkumaTadokoro** [comment]
- 初版作成（ERDシート）：https://drive.google.com/file/d/1ESu5bkRLx_cY89xBHSFBQVA6pLU58gvp/view?usp=sharing
- 国民健康保険料のデータイメージ：https://docs.google.com/spreadsheets/d/1dU9FgP4LPhGYDdYTHLh933n-oAKVigl3lFbw-2tvPRE/edit?usp=sharing

**Comment by komagata** [comment]
@IkumaTadokoro レビューさせていただきます。五月雨式に書いていきますね。

法律の名前や税金の名前は英語化するのが難しいですね。

年度がdate型のものとinteger型のものが混在しているのが気になりました。

他はいい感じだと思います〜。

**Comment by IkumaTadokoro** [comment]
@komagata 
レビューいただきありがとうございました🙇‍♂️

> 年度がdate型のものとinteger型のものが混在しているのが気になりました。

ここだけ、国民年金の方が誤っていたので、（ファイル上で）integerに変更いたしました！

**Comment by IkumaTadokoro** [comment]
以下の構成とする

![image](https://user-images.githubusercontent.com/61409641/143329764-65da8fdd-4c0c-4eb4-9bbf-233900415480.png)
